baseURL = 'http://crowd4u.github.io/'
languageCode = 'ja'
title = '融合知能デザイン研究室 エンジニアブログ'
theme = "papermod"
hasCJKLanguage = true
DefaultContentLanguage = "ja"

[permalinks]
post = "/posts/:slug/"
page = "/:slug/"

[params]
mainSections = ["posts"]
showtoc = true
ShowRssButtonInSectionTermList = true
ShowReadingTime = true
ShowPostNavLinks = true
disableSpecial1stPost = true
UseHugoToc = true
ShowShareButtons = true
ShowCodeCopyButtons = false
ShowWordCount = true
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
tocopen = true
title = '融合知能デザイン研究室 エンジニアブログ'
description = """
融合知能デザイン研究室エンジニアブログはCrowd4UやNextCrowd4Uの開発している学生によるエンジニアブログです。
私たちの研究室ではAI+人間+ビッグデータによる融合知能による研究を進め、その成果をクラウドソーシングプラットフォームなどの形で提供しています。
その開発に挑戦するチームの裏話や技術共有メモ、ちょっと聞いて欲しいことなどを発信していきます。
"""
env = "production"

[params.homeInfoParams]
Title = '融合知能デザイン研究室 エンジニアブログ'
Content = """
融合知能デザイン研究室エンジニアブログはCrowd4UやNextCrowd4Uの開発している学生によるエンジニアブログです。
私たちの研究室ではAI+人間+ビッグデータによる融合知能による研究を進め、その成果をクラウドソーシングプラットフォームなどの形で提供しています。
その開発に挑戦するチームの裏話や技術共有メモ、ちょっと聞いて欲しいことなどを発信していきます。
"""

#[params.socialIcons]
#name = "feed"
#url = "https://crowd4u.github.io/index.xml"

[params.profileMode]
enabled = false

[minify]
disableXML = true
minifyOutput = true

[taxonomies]
tags = "tags"
author = "author"

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 10
  
[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 12

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 15

[outputs]
home = ["HTML", "JSON"]